Update .travis.yml

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -51,3 +51,13 @@ matrix:
         - make -j 4
 before_script:
   - cd build
+script:
+  - cmake -DCMAKE_BUILD_TYPE=Debug ../
+  - if [[ "${TRAVIS_CPU_ARCH}" == "arm64" ]]; then
+        build-wrapper-linux-x86-64 --out-dir bw-output make all || make all;  # build-wrapper won't work on forked repositories.
+    else
+        build-wrapper-linux-aarch64 --out-dir bw-output make all || make all;
+    fi
+  - ctest --output-on-failure
+  - (cd .. && sonar-scanner) || true  # Will always fail builds on forked repositories.
+
