Update .travis.yml

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -50,15 +50,15 @@ matrix:
         - cmake -DENABLE_PROBES=false ../
         - make -j 4
 before_script:
-    - cd build
+  - cd build
 script:
-    - cmake -DCMAKE_BUILD_TYPE=Debug ../
-    - if [[ "${TRAVIS_CPU_ARCH}" == "arm64" ]]; then
-        build-wrapper-linux-x86-64 --out-dir bw-output make all || make all;  # build-wrapper won't work on forked repositories.
-      else
-        build-wrapper-linux-aarch64 --out-dir bw-output make all || make all;
-      fi
-    - ctest --output-on-failure
-    - (cd .. && sonar-scanner) || true  # Will always fail builds on forked repositories.
+  - cmake -DCMAKE_BUILD_TYPE=Debug ../
+  - if [[ "${TRAVIS_CPU_ARCH}" == "arm64" ]]; then
+       build-wrapper-linux-x86-64 --out-dir bw-output make all || make all;  # build-wrapper won't work on forked repositories.
+    else
+       build-wrapper-linux-aarch64 --out-dir bw-output make all || make all;
+    fi
+  - ctest --output-on-failure
+  - (cd .. && sonar-scanner) || true  # Will always fail builds on forked repositories.
 after_success:
     - curl -s https://codecov.io/bash > cov.sh && bash cov.sh -x "$GCOV"
